name: Build conda environment and train tiny local model

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        activate-environment: rtfm

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Update conda
      run: conda update -n base -c defaults conda

    - name: Install additional package
      run: conda run -n rtfm pip install --no-deps git+https://github.com/mlfoundations/tableshift.git

    - name: Run shell script
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate rtfm
        ./scripts/tests/train_tiny_local_test.sh
